In [1]:
coh_csv = "coh_0_600_ep2600_right_overt_70_140_all_mean_usable_ch.csv"
acc_csv = "spec70_140_acc_bad_ch_removed.csv"

import pandas as pd

coh_df = pd.read_csv(coh_csv, index_col=0)
acc_df = pd.read_csv(acc_csv, index_col=0)

coh_melt = coh_df.reset_index().melt(id_vars='index', var_name='sub', value_name='coh')
coh_melt = coh_melt.rename(columns={'index': 'ch'})

acc_melt = acc_df.reset_index().melt(id_vars='index', var_name='sub', value_name='acc')
acc_melt = acc_melt.rename(columns={'index': 'ch'})

concat_df = pd.concat([coh_melt, acc_melt[['ch', 'sub', 'acc']]], axis=1)
# 重複する列（'ch'と'sub'）のうち、最初に現れたものを残して削除
concat_df = concat_df.loc[:,~concat_df.columns.duplicated()]
concat_df.dropna(subset=['coh', 'acc'], inplace=True)
concat_df

       ch   sub       coh       acc
0    ch01  js01  0.103015  0.250000
1    ch02  js01  0.103277  0.190000
2    ch03  js01  0.096750  0.256250
3    ch04  js01  0.105585  0.177500
4    ch05  js01  0.073026  0.225000
..    ...   ...       ...       ...
903  ch24  js16  0.029635  0.149333
912  ch33  js16  0.077620  0.350667
913  ch34  js16  0.067992  0.253333
914  ch35  js16  0.050466  0.144000
916  ch37  js16  0.039645  0.165333

[725 rows x 4 columns]

In [2]:
coord_df = pd.read_csv("all_coord_multi5_and_region_speech.csv", index_col=0)
coord_df['ch'] = coord_df.index

coord_df

,x,y,z,label,sub,region,color,ch
ch01,-0.013797,-0.049520,0.053301,Precuneus_L,js01,Parietal_L,#1f77b4,ch01
ch02,-0.010444,-0.049628,0.057675,Precuneus_L,js01,Parietal_L,#1f77b4,ch02
ch03,-0.012236,-0.054193,0.048475,Precuneus_L,js01,Parietal_L,#1f77b4,ch03
ch04,-0.007928,-0.054147,0.052827,Precuneus_L,js01,Parietal_L,#1f77b4,ch04
ch05,-0.004637,-0.027661,0.075573,Paracentral_Lobule_L,js01,Parietal_L,#1f77b4,ch05
...,...,...,...,...,...,...,...,...
ch36,-0.036872,0.012869,0.035202,Frontal_Mid_L,js16,Frontal_L,#ffbb78,ch36
ch37,-0.042078,0.013788,0.033887,Frontal_Inf_Oper_L,js16,Frontal_Broca_L,#f7b6d2,ch37
ch38,-0.045674,0.012042,0.035994,Frontal_Mid_L,js16,Frontal_L,#ffbb78,ch38
ch39,-0.044171,0.017452,0.033812,Frontal_Inf_Oper_L,js16,Frontal_Broca_L,#f7b6d2,ch39
ch40,-0.047335,0.015657,0.035771,Frontal_Mid_L,js16,Frontal_L,#ffbb78,ch40

In [5]:
# chとsub列でマージ
all_sub_df = pd.merge(concat_df, coord_df, on=['sub', 'ch'], how='outer')
all_sub_df.head(10)
all_sub_df.to_csv("all_sub_coh_acc_multi5.csv")

In [4]:
sorted(coord_df['label'].unique())

['Amygdala_L',
 'Angular_L',
 'Calcarine_L',
 'Caudate_L',
 'Cerebellum_4_5_L',
 'Cerebellum_6_L',
 'Cerebellum_Crus1_L',
 'Cuneus_L',
 'Frontal_Inf_Oper_L',
 'Frontal_Inf_Oper_R',
 'Frontal_Inf_Orb_L',
 'Frontal_Inf_Orb_R',
 'Frontal_Inf_Tri_L',
 'Frontal_Inf_Tri_R',
 'Frontal_Mid_L',
 'Frontal_Mid_Orb_L',
 'Frontal_Mid_R',
 'Frontal_Sup_L',
 'Frontal_Sup_Orb_L',
 'Frontal_Sup_R',
 'Fusiform_L',
 'Heschl_L',
 'Insula_L',
 'Lingual_L',
 'Occipital_Inf_L',
 'Occipital_Mid_L',
 'Occipital_Sup_L',
 'ParaHippocampal_L',
 'Paracentral_Lobule_L',
 'Parietal_Inf_L',
 'Parietal_Sup_L',
 'Postcentral_L',
 'Postcentral_R',
 'Precentral_L',
 'Precentral_R',
 'Precuneus_L',
 'Rectus_L',
 'Rolandic_Oper_L',
 'Rolandic_Oper_R',
 'SupraMarginal_L',
 'Temporal_Inf_L',
 'Temporal_Mid_L',
 'Temporal_Pole_Mid_L',
 'Temporal_Pole_Sup_L',
 'Temporal_Pole_Sup_R',
 'Temporal_Sup_L',
 'Temporal_Sup_R',
 'no_label_found']

# VEOG

In [2]:
coh_csv = "coh_0_600_ep2600_r_up_overt_70_140_all_mean_usable_ch.csv"
acc_csv = "spec70_140_acc_bad_ch_removed.csv"

import pandas as pd

coh_df = pd.read_csv(coh_csv, index_col=0)
acc_df = pd.read_csv(acc_csv, index_col=0)

coh_melt = coh_df.reset_index().melt(id_vars='index', var_name='sub', value_name='coh')
coh_melt = coh_melt.rename(columns={'index': 'ch'})

acc_melt = acc_df.reset_index().melt(id_vars='index', var_name='sub', value_name='acc')
acc_melt = acc_melt.rename(columns={'index': 'ch'})

concat_df = pd.concat([coh_melt, acc_melt[['ch', 'sub', 'acc']]], axis=1)
# 重複する列（'ch'と'sub'）のうち、最初に現れたものを残して削除
concat_df = concat_df.loc[:,~concat_df.columns.duplicated()]
concat_df.dropna(subset=['coh', 'acc'], inplace=True)
concat_df

coord_df = pd.read_csv("all_coord_multi5_and_region_speech.csv", index_col=0)
coord_df['ch'] = coord_df.index

# chとsub列でマージ
all_sub_df = pd.merge(concat_df, coord_df, on=['sub', 'ch'], how='outer')
all_sub_df.head(10)
all_sub_df.to_csv("all_sub_coh_acc_multi5_veog.csv")